version: "3.9"

services:
  database:
    image: postgres
    container_name: entregaDB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=paladino
      - POSTGRES_DB=entregaDB
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
